### ISSUE TITLE
Support request - How to access UserData from different Plugin

### ISSUE THREAD

**Issue by dkyme** [picoauth/picoauth#3]
I'd like to use the UserData in another Plugin dependent on PicoAuth.

Since I'm more a copy'n'paste selfdidactic , than a programmer, could you help me to access PicoAuth from another Plugin?

Thank you for directions,
Cornelius

**Comment by tumapav** [comment]
From your plugin, you can ask Pico instance to give you an instance of the PicoAuth plugin. Each plugin gets the Pico instance in it's constructor.

So you can use:
```
$picoAuth = $pico->getPlugin('PicoAuth');
```
Reference of `getPlugin()` here: https://github.com/picocms/Pico/blob/master/lib/Pico.php#L872

Then you can get the `User` instance.

```
$user = $picoAuth->getUser();
```

On which you can do for example:
```
$user->getAuthenticated()  // is user logged in?
$user->getAttribute('attr')   // returns attribute value or null if not set
$user->getId()   //primary user identifier
$user->getDisplayName()  //display name (if available)
```
Full reference of `User` object is here https://github.com/picoauth/picoauth/blob/master/src/User.php
