### ISSUE TITLE
Permission issues, I guess.

### ISSUE THREAD

**Issue by notakoder** [picoauth/picoauth#4]
Ok, first things first.

I started a new Pico project using the pre bundled release (all works fine), I then extracted the contents of `PicoAuth` into the folder `/plugins`. Right after this step, the main home page throws a `HTTP 500` error. I had faced a similar issue with another Pico project and giving `go+rx` permissions recursively to the `PicoAuth` folder fixed it. But it does not work with this test project anymore, even after giving `go+rwx` permissions recursively. The moment I remove the `PicoAuth` folder from inside `/plugins`, the website is back.

I checked the Apache error logs and found an error
```
PHP Fatal error:  Uncaught Twig_Error_Syntax: Unknown "url" filter. Did you mean "url_encode"? in /var/www/test/themes/default/index.twig:34...
```
Line 34 of the corresponding twig page says `<img src="{{ pages["_meta"].meta.logo|url }}" alt="" />` 

When I change the theme (I have a customised one), this error gets fixed. I am not sure who is wrong here: the default theme or PicoAuth. But what I wonder here taking Pico and themes as 'a single entity' is, whether it a good thing to ensure that the default plugin settings works with the default theme?

**Comment by tumapav** [comment]
Hello,
it seems like a problem related to installing the plugin from a release bundle instead of using a composer installation. The v1.0.0 release of Picoauth comes with vendor directory based on Pico 2.0 dependencies, but I assume you installed it into the current 2.1 release. I think what happened is that version of Twig bundled into the plugin release as dependency of Pico has replaced the newer version of Twig in your current installation making some template functions like `|url` unavailable.

I updated the plugin release with the newest Pico 2.1 installation and you can try that be getting v1.0.1 from https://github.com/picoauth/picoauth/releases .

To avoid any future possible collisions like this, you can install pico and the plugin using composer.
```
composer create-project picocms/pico-composer pico
composer require picocms/composer-installer:^1.0
composer require picoauth/picoauth
```

**Comment by notakoder** [comment]
The new bundle worked fine for some time until I hit an issue later with the localhost project and the error logs says this.

```
[Thu Jul 22 13:31:48.334527 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(/var/www/test/plugins/PicoAuth/vendor/symfony/yaml/Parser.php): failed to open stream: Permission denied in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.334575 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(): Failed opening '/var/www/test/plugins/PicoAuth/vendor/composer/../symfony/yaml/Parser.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.334727 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(/var/www/test/plugins/PicoAuth/vendor/symfony/yaml/Inline.php): failed to open stream: Permission denied in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.334746 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(): Failed opening '/var/www/test/plugins/PicoAuth/vendor/composer/../symfony/yaml/Inline.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.336812 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(/var/www/test/plugins/PicoAuth/vendor/symfony/yaml/Yaml.php): failed to open stream: Permission denied in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.336843 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(): Failed opening '/var/www/test/plugins/PicoAuth/vendor/composer/../symfony/yaml/Yaml.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.336998 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(/var/www/test/plugins/PicoAuth/vendor/symfony/yaml/Unescaper.php): failed to open stream: Permission denied in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.337014 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(): Failed opening '/var/www/test/plugins/PicoAuth/vendor/composer/../symfony/yaml/Unescaper.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.337570 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(/var/www/test/plugins/PicoAuth/vendor/symfony/http-foundation/Request.php): failed to open stream: Permission denied in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.337602 2021] [php7:warn] [pid 5417] [client ::1:42690] PHP Warning:  include(): Failed opening '/var/www/test/plugins/PicoAuth/vendor/composer/../symfony/http-foundation/Request.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/vendor/composer/ClassLoader.php on line 444, referer: http://localhost/
[Thu Jul 22 13:31:48.337665 2021] [php7:error] [pid 5417] [client ::1:42690] PHP Fatal error:  Uncaught Error: Class 'Symfony\\Component\\HttpFoundation\\Request' not found in /var/www/test/plugins/PicoAuth/src/PicoAuthPlugin.php:666\nStack trace:\n#0 /var/www/test/plugins/PicoAuth/src/PicoAuthPlugin.php(211): PicoAuth\\PicoAuthPlugin->init()\n#1 [internal function]: PicoAuth\\PicoAuthPlugin->onRequestUrl('')\n#2 /var/www/test/plugins/PicoAuth/src/PicoAuthPlugin.php(162): call_user_func_array(Array, Array)\n#3 /var/www/test/plugins/PicoAuth/PicoAuth.php(69): PicoAuth\\PicoAuthPlugin->handleEvent('onRequestUrl', Array)\n#4 /var/www/test/plugins/PicoDeprecated/PicoDeprecated.php(319): PicoAuth->handleEvent('onRequestUrl', Array)\n#5 /var/www/test/plugins/PicoDeprecated/lib/AbstractPicoPluginApiCompatPlugin.php(81): PicoDeprecated->triggerEvent(2, 'onRequestUrl', Array)\n#6 /var/www/test/plugins/PicoDeprecated/lib/AbstractPicoPluginApiCompatPlugin.php(49): AbstractPicoPluginApiCompatPlugin->triggerEvent('onRequestUrl', Array)\n#7 /var/www/test/plugins/PicoD in /var/www/test/plugins/PicoAuth/src/PicoAuthPlugin.php on line 666, referer: http://localhost/
```

Note that my production project is working fine with the new PicoAuth bundle. I am facing issues only with my localhost project, which gets resolved the moment I remove the `/plugins/PicoAuth` directory. And this could be because I did not install PicoAuth using composer as you guessed it right. My Pico installation was not done using composer and the [documentation](https://github.com/picoauth/picoauth#install) explicitly mentioned that, "(possible only if you installed Pico using composer-installer)", which is why I used the bundled release.

--- UPDATE---
Anyway, I created a new project using composer, installed `PicoAuth` using composed, copied the `content` and `themes` folder from the old one, and so far things are good.
Thanks for the help. Closing the issue.
