### ISSUE TITLE
Footnotes messed up

### ISSUE THREAD

**Issue by notakoder** [picoauth/picoauth#5]
When using PicoAuth, I noticed that footnotes mentioned md pages are rendered with html tags itself, as follows

`<p>Lorem Ipsum.&#160;<a href="#fnref1:testnote" rev="footnote" class="footnote-backref">&#8617;</a></p>`
 
Here is the html render of the footnote on the website taken from the source page (Ctrl+u)

```
<li id="fn:testnote">
&lt;p&gt;Lorem Ipsum.&amp;#160;&lt;a href="#fnref1:testnote" rev="footnote" class="footnote-backref"&gt;&amp;#8617;&lt;/a&gt;&lt;/p&gt;
</li>
```

If I remove the `/plugins/PicoAuth` folder, this issue is fixed.

**Comment by tumapav** [comment]
It seems like the same issue as in #4 . If it turns out it is a different problem, let me know. For now marking it duplicate.
